# Generated by Django 2.2.6 on 2022-11-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221111_0109'),
        ('posts', '0007_auto_20221029_2246'),
    ]

    operations = [
    ]
